version: "3.7"

services:
  app:
    container_name: website
    image: go-vite-react-ts-app
    build:
      context: ./src
      dockerfile: ../Dockerfile
    environment:
      - WS_SERVER_PORT=${WS_SERVER_PORT:-${WS_DEFAULT_SERVER_PORT}}
    env_file:
      - ./src/env/.env.docker
      - ./src/env/.env.docker.local
    hostname: localhost
    ports:
      - target: ${WS_SERVER_PORT:-${WS_DEFAULT_SERVER_PORT}} 
        published: ${WS_HOST_PORT:-${WS_DEFAULT_HOST_PORT}}
        protocol: tcp
        mode: host
